# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931d2b74220e00a48ed93d99132bce3a114de8aced4263a64168a9f988b987557be3f390c369a36eeecb56342a45d5ca13d92a08a1eeac584901c309624d553e

test:
  secret_key_base: c1500c30ead05db7db085392c4e993bebba2dc53d741a47fe1d9422ebad591ca2f724d157e83bf195ef90685cb657ad852dfb182b792f4ced3194e8b11a55a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
